[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = ["unused-param"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# --snip--
[rpc_endpoints]
optimism = "${RPC_MAINNET}"
mainnet = "${RPC_MAINNET}"
optimism_sepolia = "https://optimism-sepolia.blockpi.network/v1/rpc/public"
base_sepolia = "https://sepolia.base.org"
mainnet_sepolia = "https://eth-sepolia.public.blastapi.io"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc/"
berachain_bartio = "https://bartio.rpc.berachain.com/"
zora_sepolia = "https://sepolia.rpc.zora.energy/"
blast_sepolia = "https://sepolia.blast.io/"
morph_holesky = "https://rpc-quicknode-holesky.morphl2.io/"
linea_sepolia = "https://rpc.linea.build/"